apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: ClusterIP  # Use ClusterIP for internal access or change to LoadBalancer for external access
  ports:
    - port: 8000
      targetPort: 80
  selector:
    app: nginx
