apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: hello-world
spec:
  serviceAccountName: argo-workflow-argo-workflows-workflow-controller
  entrypoint: hello
  templates:
  - name: hello
    container:
      image: alpine
      command: [echo]
      args: ["hello world"]
      resources:
        limits:
          memory: 32Mi
          cpu: 100m
