apiVersion: v1
kind: ServiceAccount
metadata:
  name: workflows-user
  namespace: argo-workflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflows-user-role
  namespace: argo-workflow
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["workflowtaskresults"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflows-user-rolebinding
  namespace: argo-workflow
subjects:
  - kind: ServiceAccount
    name: workflows-user
    namespace: argo-workflow
roleRef:
  kind: Role
  name: workflows-user-role
  apiGroup: rbac.authorization.k8s.io
