apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argo-workflows
spec:
  project: default
  source:
    repoURL: git@github.com:elimayost/argocd.git
    targetRevision: HEAD
    path: argo-workflows
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-workflows
