apiVersion: v2
name: argo-cd
description: A Helm chart that pulls argo cd chart as a dependency
version: 0.0.1
type: application
dependencies:
  - name: argo-cd
    version: "7.8.7"
    repository: "https://argoproj.github.io/argo-helm"
