apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
spec:
  project: default
	syncPolicy:
		automated:
			selfHeal: true
  source:
    repoURL: git@github.com:elimayost/helm-charts.git
    targetRevision: HEAD
    path: argo-workflows
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-workflows
